[FILTER]
    Name          lua
    Match         docker.raw
    script        /etc/fluent-bit/scripts/parse_docker.lua
    call          parse_docker_log

[FILTER]
    Name          rewrite_tag
    Match         docker.raw
    Rule          route_key ^(.+)$ docker.test.$1 true